### ISSUE TITLE
Compression handler does not account for copression making packet larger

### ISSUE THREAD

**Issue by TechnoMancer** [BonsaiDen/cobalt-rs#2]
The handler for compressing a packet expects compression to be done in-place and allows no mechanism for the 'compressed' form to be larger than the original.  Lossless compression cannot compress arbitrary data so expecting packets to always become smaller is nonsensical.

**Comment by BonsaiDen** [comment]
Oops, definitely an oversight on my end. Will fix this one shortly :)

**Comment by BonsaiDen** [comment]
@TechnoMancer Version 0.11.0 has just been published which takes care of the issues. The change however is breaking since the method signature had to change. The method should now return a `Vec<u8>` with the complete packet data (including headers), but for convenience it now also receives a `Vec<u8>` which is already pre-filled with the packet's headers and can simply extended by the compressed data before it is returned.
